"""Process disclosures are execution metadata, not model-authored market claims."""

import asyncio

import pytest
from pydantic import ValidationError

from backend.agent import research
from backend.schemas import Costs, ReportDraft, ReportSubmission, ResearchInput, SearchArgs
from backend.tools import ResearchTools, definitions
from tests.helpers import ModelFixture, SearchFixture, call, draft


def submission():
    return call("submit_report", draft())["tool_calls"][0]["function"]["arguments"]


@pytest.mark.parametrize(
    "text",
    [
        "This research did not independently verify demand.",
        "No evidence exists that construction workers want heated lunch boxes.",
        "Demand is low because workers cannot afford these products.",
    ],
)
def test_all_model_limitation_prose_is_forbidden_even_if_it_sounds_like_process(text):
    data = submission()
    data["limitations"] = [text]
    with pytest.raises(ValidationError) as error:
        ReportSubmission.model_validate(data)
    assert error.value.errors()[0]["type"] == "extra_forbidden"
    assert error.value.errors()[0]["loc"] == ("limitations",)


def test_native_contract_has_no_limitation_field_and_public_contract_keeps_strings():
    schema = definitions(["submit_report"])[0]["function"]["parameters"]
    assert "limitations" not in schema["properties"]
    assert "limitations" not in schema["required"]
    assert schema["additionalProperties"] is False
    assert ReportDraft.model_json_schema()["properties"]["limitations"]["items"] == {
        "type": "string"
    }


def test_disclosures_follow_actual_sources_prices_costs_and_failures():
    tools = ResearchTools(SearchFixture())
    initial = tools.process_limitations()
    assert not any(
        "full source pages" in x or "Price mentions" in x or "steps failed" in x for x in initial
    )
    assert any("No user-supplied cost" in x for x in initial)
    asyncio.run(tools.execute("search_web", SearchArgs(query="grinder")))
    tools.failures.append("UNTRUSTED ASSERTION: no market exists")
    report = tools.validate_report(ReportSubmission.model_validate(submission()))
    limits = report["limitations"]
    assert all(isinstance(x, str) for x in limits)
    assert limits == tools.process_limitations()
    assert any("full source pages were not retrieved" in x for x in limits)
    assert any("Price mentions" in x for x in limits)
    assert any("steps failed" in x for x in limits)
    assert not any("UNTRUSTED" in x or "no market exists" in x for x in limits)
    assert any("does not perform independent product testing" in x for x in limits)
    # A different source kind cannot acquire an unsupported snippet-only disclosure.
    tools.sources["S1"]["kind"] = "other"
    assert not any("full source pages" in x for x in tools.process_limitations())


def test_supplied_costs_are_distinct_from_executed_calculation():
    costs = Costs(sale_price=100, unit_cost=30, shipping=5, other_costs=0, fee_percent=10)
    tools = ResearchTools(SearchFixture(), costs)
    assert any("calculation was not performed" in x for x in tools.process_limitations())
    asyncio.run(tools.execute("calculate_margin", None))
    limits = tools.process_limitations()
    assert any("not forecasts or verified business results" in x for x in limits)
    assert not any("not performed" in x or "No user-supplied" in x for x in limits)


def test_internal_resolved_report_cannot_smuggle_arbitrary_limitations():
    tools = ResearchTools(SearchFixture())
    asyncio.run(tools.execute("search_web", SearchArgs(query="grinder")))
    resolved = tools.resolve_references(ReportSubmission.model_validate(submission()))
    resolved.limitations = ["No evidence exists that people want this product."]
    with pytest.raises(ValueError, match="generated by the server"):
        tools.validate_report(resolved)


@pytest.mark.parametrize("unsolicited", [False, True])
def test_model_generated_limitations_cannot_enter_the_report(unsolicited):
    good = call("submit_report", draft())
    responses = [call("search_web", {"query": "grinder"})]
    if unsolicited:
        bad = call("submit_report", draft())
        bad["tool_calls"][0]["function"]["arguments"]["limitations"] = [
            "Demand is low because workers cannot afford these products."
        ]
        responses.append(bad)
    responses.append(good)

    model = ModelFixture(responses)

    async def scenario():
        async def emit(*args):
            pass

        return await research(
            ResearchInput(idea="heated lunch box"), model, ResearchTools(SearchFixture()), 2, emit
        )

    report, status = asyncio.run(scenario())
    assert status == "completed"
    assert all("Demand is low" not in x for x in report["limitations"])
    if unsolicited:
        assert "Omit limitations entirely" in model.messages[-1][-1]["content"]
    assert len(model.messages) == (3 if unsolicited else 2)
